# Generated by Django 6.0.1 on 2026-06-25 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_comentarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comentarios',
            new_name='Comentario',
        ),
    ]
